export const governanceMarkdown = (rules: string[]): string => [
  "# Portal Memory Governance",
  "",
  ...(rules.length > 0 ? ["## House rules (always apply)", ...rules.map((rule) => `- ${rule}`), ""] : []),
  "## Writing discipline",
  "- No em dashes. Use commas, colons, parentheses, or vs./or/to.",
  "- No invented numbers. Cite a source file for any figure, or label it an estimate.",
  "- No time estimates for work. Use size units (lines, files) instead.",
  "- Cite the knowledge-base file path any claim is grounded in.",
  "",
  "## Memory conventions",
  "- Each memory file has frontmatter: name, description, type (user|feedback|project|reference).",
  "- MEMORY.md is an index (one line per memory), not a dump; keep it under 200 lines.",
  "- Convert relative dates to absolute. Merge into existing files rather than duplicating.",
  "- Shared memory is group-scoped: memory/shared/<group>/ means visible to everyone in <group>.",
  "  Choose the narrowest group that covers everyone who needs the fact. Never move a fact from a",
  "  narrower group into a broader one, and never restate a restricted fact in a broader group's file.",
  "- Private memory (memory/users/<you>/) is the right home for anything you are unsure how to classify.",
].join("\n");
